spring:
  application:
    name: pastebin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pastebin
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
